CREATE TABLE IF NOT EXISTS public."RadiusUsers"
(
    "Id"                   integer generated by default as identity
        constraint "PK_RadiusUsers"
            primary key,
    "ExternalId"           integer                  not null,
    "Username"             text,
    "Firstname"            text,
    "Lastname"             text,
    "City"                 text,
    "Phone"                text,
    "ProfileId"            integer,
    "Balance"              numeric                  not null,
    "LoanBalance"          numeric                  not null,
    "Expiration"           timestamp with time zone,
    "LastOnline"           timestamp with time zone,
    "ParentId"             integer,
    "Email"                text,
    "StaticIp"             text,
    "Enabled"              boolean                  not null,
    "Company"              text,
    "Notes"                text,
    "SimultaneousSessions" integer                  not null,
    "Address"              text,
    "ContractId"           text,
    "NationalId"           text,
    "MikrotikIpv6Prefix"   text,
    "GroupId"              integer,
    "GpsLat"               text,
    "GpsLng"               text,
    "Street"               text,
    "SiteId"               integer,
    "PinTries"             integer                  not null,
    "RemainingDays"        integer                  not null,
    "OnlineStatus"         integer                  not null,
    "UsedTraffic"          bigint                   not null,
    "AvailableTraffic"     bigint                   not null,
    "ParentUsername"       text,
    "DebtDays"             integer                  not null,
    "IsDeleted"            boolean                  not null,
    "DeletedAt"            timestamp with time zone,
    "WorkspaceId"          integer                  not null,
    "CreatedAt"            timestamp with time zone not null,
    "UpdatedAt"            timestamp with time zone not null,
    "LastSyncedAt"         timestamp with time zone
);

-- Create an index on Username for faster lookups
CREATE INDEX IF NOT EXISTS idx_radiususers_username ON public."RadiusUsers"("Username");
