// =============================================================================
// OpenRadius Application Configuration
// =============================================================================
// Resolution order (first non-empty wins):
//   1. Runtime config (window.__RUNTIME_CONFIG__) — injected by Docker entrypoint
//   2. Build-time env (import.meta.env.VITE_*) — baked into the bundle
//   3. Defaults — localhost for development
// =============================================================================

/**
 * Runtime configuration shape injected via /env-config.js at container startup.
 * Generated by docker-entrypoint.sh from the DOMAIN environment variable.
 */
interface RuntimeConfig {
  VITE_API_URL?: string
  VITE_FRONTEND_URL?: string
  VITE_SEQ_URL?: string
  VITE_KEYCLOAK_URL?: string
  VITE_KEYCLOAK_REALM?: string
  VITE_KEYCLOAK_CLIENT_ID?: string
}

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: RuntimeConfig
  }
}

/** Resolve a config value: runtime → build-time → default */
function resolve(runtimeKey: keyof RuntimeConfig, buildTimeEnv: string | undefined, fallback: string): string {
  return window.__RUNTIME_CONFIG__?.[runtimeKey] || buildTimeEnv || fallback
}

export const appConfig = Object.freeze({
  appName: 'OpenRadius',
  version: '1.0.0',
  api: Object.freeze({
    baseUrl: resolve('VITE_API_URL', import.meta.env.VITE_API_URL, 'http://localhost:5000'),
    timeout: 30_000,
  }),
  frontend: Object.freeze({
    baseUrl: resolve('VITE_FRONTEND_URL', import.meta.env.VITE_FRONTEND_URL, 'http://localhost:5173'),
  }),
  seq: Object.freeze({
    url: resolve('VITE_SEQ_URL', import.meta.env.VITE_SEQ_URL, 'http://localhost:5341'),
  }),
  keycloak: Object.freeze({
    url: resolve('VITE_KEYCLOAK_URL', import.meta.env.VITE_KEYCLOAK_URL, 'http://localhost:8080'),
    realm: resolve('VITE_KEYCLOAK_REALM', import.meta.env.VITE_KEYCLOAK_REALM, 'openradius'),
    clientId: resolve('VITE_KEYCLOAK_CLIENT_ID', import.meta.env.VITE_KEYCLOAK_CLIENT_ID, 'openradius-web'),
  }),
  theme: {
    defaultMode: 'light' as 'light' | 'dark',
    defaultColor: 'purple' as string,
    availableColors: [
      { name: 'Blue', value: 'blue', class: 'oklch(0.583 0.187 262.881)' },
      { name: 'Green', value: 'green', class: 'oklch(0.552 0.166 152.482)' },
      { name: 'Purple', value: 'purple', class: 'oklch(0.631 0.242 297.696)' },
      { name: 'Red', value: 'red', class: 'oklch(0.637 0.237 27.325)' },
      { name: 'Orange', value: 'orange', class: 'oklch(0.705 0.186 56.049)' },
    ],
  },
  i18n: Object.freeze({
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar'] as readonly string[],
  }),
})

export type AppConfig = typeof appConfig

// Log active configuration source in development
if (import.meta.env.DEV) {
  const source = window.__RUNTIME_CONFIG__?.VITE_API_URL
    ? 'runtime (env-config.js)'
    : import.meta.env.VITE_API_URL
      ? 'build-time (.env)'
      : 'defaults (localhost)'
  console.info(`[AppConfig] Source: ${source} | API: ${appConfig.api.baseUrl} | Auth: ${appConfig.keycloak.url}`)
}
